apiVersion: apps/v1
kind: Deployment
metadata:
  name: galgal-user-login
  labels:
    app.kubernetes.io/name: galgal-user-login
    app.kubernetes.io/instance: galgal-user-login
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: galgal-user-login
      app.kubernetes.io/instance: galgal-user-login
  template:
    metadata:
      labels:
        app.kubernetes.io/name: galgal-user-login
        app.kubernetes.io/instance: galgal-user-login
    spec:
      containers:
        - name: galgal-user-login
          image: asia.gcr.io/poc-innovation-iot/galgal-user-login:TAG
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: galgal-user-login-configmap-env
            - secretRef:
                name: galgal-user-login-secret-env
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            timeoutSeconds: 10
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            timeoutSeconds: 10
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 400m
              memory: 256Mi
          volumeMounts:
            - name: galgal-user-login-configmap-file
              mountPath: /config
              readOnly: true

      volumes:
        - name: galgal-user-login-configmap-file
          configMap:
            name: galgal-user-login-configmap-file
